#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sino.Droid.SlideDateTimePicker.Resource", IsApplication=false)]

namespace Sino.Droid.SlideDateTimePicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int sino_sdtp_gray_holo_dark = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int sino_sdtp_gray_holo_light = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int sino_sdtp_selection_divider = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public static int buttonHorizontalDivider = 2131034118;
			
			// aapt resource value: 0x7f050008
			public static int buttonVerticalDivider = 2131034120;
			
			// aapt resource value: 0x7f050007
			public static int cancelButton = 2131034119;
			
			// aapt resource value: 0x7f050000
			public static int customTab = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int datePicker = 2131034114;
			
			// aapt resource value: 0x7f050009
			public static int okButton = 2131034121;
			
			// aapt resource value: 0x7f050004
			public static int slidingTabLayout = 2131034116;
			
			// aapt resource value: 0x7f050001
			public static int tabText = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int timePicker = 2131034115;
			
			// aapt resource value: 0x7f050005
			public static int viewPager = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int sino_sdtp_custom_tab = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int sino_sdtp_fragment_date = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int sino_sdtp_fragment_time = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int sino_sdtp_slide_date_time_picker = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
