#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlideDateTimePicker.Sample.Resource", IsApplication=true)]

namespace SlideDateTimePicker.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Sino.Droid.SlideDateTimePicker.Resource.Color.sino_sdtp_gray_holo_dark = global::SlideDateTimePicker.Sample.Resource.Color.sino_sdtp_gray_holo_dark;
			global::Sino.Droid.SlideDateTimePicker.Resource.Color.sino_sdtp_gray_holo_light = global::SlideDateTimePicker.Sample.Resource.Color.sino_sdtp_gray_holo_light;
			global::Sino.Droid.SlideDateTimePicker.Resource.Drawable.sino_sdtp_selection_divider = global::SlideDateTimePicker.Sample.Resource.Drawable.sino_sdtp_selection_divider;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.buttonHorizontalDivider = global::SlideDateTimePicker.Sample.Resource.Id.buttonHorizontalDivider;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.buttonVerticalDivider = global::SlideDateTimePicker.Sample.Resource.Id.buttonVerticalDivider;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.cancelButton = global::SlideDateTimePicker.Sample.Resource.Id.cancelButton;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.customTab = global::SlideDateTimePicker.Sample.Resource.Id.customTab;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.datePicker = global::SlideDateTimePicker.Sample.Resource.Id.datePicker;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.okButton = global::SlideDateTimePicker.Sample.Resource.Id.okButton;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.slidingTabLayout = global::SlideDateTimePicker.Sample.Resource.Id.slidingTabLayout;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.tabText = global::SlideDateTimePicker.Sample.Resource.Id.tabText;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.timePicker = global::SlideDateTimePicker.Sample.Resource.Id.timePicker;
			global::Sino.Droid.SlideDateTimePicker.Resource.Id.viewPager = global::SlideDateTimePicker.Sample.Resource.Id.viewPager;
			global::Sino.Droid.SlideDateTimePicker.Resource.Layout.sino_sdtp_custom_tab = global::SlideDateTimePicker.Sample.Resource.Layout.sino_sdtp_custom_tab;
			global::Sino.Droid.SlideDateTimePicker.Resource.Layout.sino_sdtp_fragment_date = global::SlideDateTimePicker.Sample.Resource.Layout.sino_sdtp_fragment_date;
			global::Sino.Droid.SlideDateTimePicker.Resource.Layout.sino_sdtp_fragment_time = global::SlideDateTimePicker.Sample.Resource.Layout.sino_sdtp_fragment_time;
			global::Sino.Droid.SlideDateTimePicker.Resource.Layout.sino_sdtp_slide_date_time_picker = global::SlideDateTimePicker.Sample.Resource.Layout.sino_sdtp_slide_date_time_picker;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int sino_sdtp_gray_holo_dark = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int sino_sdtp_gray_holo_light = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sino_sdtp_selection_divider = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int buttonHorizontalDivider = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int buttonVerticalDivider = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int cancelButton = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int customTab = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int datePicker = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int okButton = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int slidingTabLayout = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int tabText = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int timePicker = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int viewPager = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int sino_sdtp_custom_tab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int sino_sdtp_fragment_date = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int sino_sdtp_fragment_time = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int sino_sdtp_slide_date_time_picker = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
